### ISSUE TITLE
hard pinning dependencies will lead to problems ...

### ISSUE THREAD

**Issue by onkelbeh** [IceBotYT/peco-outage-api#1]
Hi,
if possible, you should replace
```
install_requires =
    aiohttp==3.8.1
    pydantic==1.9.0
```
with
```
install_requires =
    aiohttp>=3.8.1
    pydantic>=1.9.0
```

Otherwise the next bump of one of these will lead to problems.
PS: hope you don't mind I'll use your component for https://github.com/onkelbeh/HomeAssistantRepository

**Comment by IceBotYT** [comment]
Should be solved now. Thanks for letting me know 😁

**Comment by onkelbeh** [comment]
Thank you, too.
